Implement face rect detection
KimDarren/FaceCropper pull request #3
Opened 2017-08-12 00:26 UTC by svetlanama

@KimDarren Please review implementation of “face rect detection”

2017-08-13 14:40 UTC, KimDarren commented
Thanks for your contribution. I'll review your request asap..!
Give me a second 😄

2017-08-14 01:01 UTC, KimDarren requested changes

2017-08-14 01:01 UTC, KimDarren commented on FaceCropper/Classes/FaceCropper.swift
> +      print(error)
I think to print error is not needed in this library, and the completion handler have to be called when any error occurred like this,
```swift
completion(.failure(error))
```

2017-08-14 01:01 UTC, KimDarren commented on FaceCropper/Classes/FaceCropper.swift
> +      print(error)
To print error is not what this library need to do. It's just what the developers using this library need to do if they want. 😄

2017-08-14 12:08 UTC, svetlanama commented on FaceCropper/Classes/FaceCropper.swift
> +      print(error)
@KimDarren  Done!

2017-12-19 18:44 UTC, closed without merging